version: '3'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      PMA_USER: your_username
      PMA_PASSWORD: your_password

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./ssl:/etc/ssl/certs

