FROM php:7.4-cli

WORKDIR /app

# Install dependencies
RUN apt-get update \
    && apt-get install -y git \
    && rm -rf /var/lib/apt/lists/*


# Install dependencies using Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN composer install --no-dev --optimize-autoloader

# Copy your WebSocket server code to the container
COPY websocket_server.php /app

CMD [ "php", "/PHP/websocket_server.php" ]
